# Setup
title:        Let's fly a new flag over Nashville
tagline:      The Nashville Flag Project aims to design a bold & representative symbol for our city that promotes unity and civic pride. Let's create it together.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       The Nashville Flag Society
  url:        http://nashvilleflagsociety.org

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
